name: mri_creation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torchio
      - SimpleITK
      - scipy
      - matplotlib
      - numpy
      - jupyter
      - ipykernel
