sonar.organization=drcandacemakedamoore
sonar.projectKey=drcandacemakedamoore_dissector
sonar.host.url=https://sonarcloud.io
sonar.sources=src/dissector/
sonar.tests=tests/
sonar.links.homepage=https://github.com/drcandacemakedamoore/dissector
sonar.links.scm=git@github.com:drcandacemakedamoore/dissector
sonar.links.issue=https://github.com/drcandacemakedamoore/dissector/issues
sonar.links.ci=https://github.com/drcandacemakedamoore/dissector/actions
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-result.xml
sonar.python.pylint.reportPaths=pylint-report.txt
